"""All capability modules must be imported so that HandlerBase subclasses are registered."""

from heralding.capabilities import (  # noqa: F401
    ftp,
    http,
    http_proxy,
    https,
    imap,
    imaps,
    mqtt,
    mqtts,
    mysql,
    pop3,
    pop3s,
    postgresql,
    rdp,
    redis,
    smtp,
    smtps,
    socks5,
    ssh,
    submission,
    telnet,
    vnc,
)
