import pytest

from heralding.tests.conftest import make_options

# RDP logins are verified manually with xfreerdp (see the milestone C plan, rule 5);
# robustness is covered by test_fuzz.py.


def _rdp_options(**extra):
    return make_options(
        banner="",
        cert={
            "common_name": "*",
            "country": "US",
            "state": "None",
            "locality": "None",
            "organization": "None",
            "organizational_unit": "None",
            "valid_days": 365,
            "serial_number": 0,
        },
        **extra,
    )


def test_tls_server_data_has_no_proprietary_rsa_material():
    import struct

    from heralding.libs.msrdp.pdu import ServerData

    # Inspect generated server data only; client wire validation uses FreeRDP.
    data = ServerData.generate(1, channel_count=4)
    pos = 0
    blocks = {}
    while pos < len(data):
        kind, length = struct.unpack_from("<HH", data, pos)
        blocks[kind] = data[pos : pos + length]
        pos += length
    assert len(blocks[0x0C02]) == 12
    assert struct.unpack_from("<II", blocks[0x0C02], 4) == (0, 0)
    assert struct.unpack_from("<HH", blocks[0x0C03], 4) == (1003, 4)
    assert struct.unpack_from("<4H", blocks[0x0C03], 8) == (1004, 1005, 1006, 1007)


@pytest.mark.parametrize("channel_count", [0, 1, 3, 4, 8, 31])
def test_user_channel_does_not_alias_static_or_io_channels(channel_count):
    from heralding.libs.msrdp.pdu import MCSAttachUserConfirmPDU

    confirmation = MCSAttachUserConfirmPDU(channel_count)
    assert confirmation.user_channel_id not in {1003, *range(1004, 1004 + channel_count)}
    # Inspect only our server response; complete client flows use FreeRDP.
    assert int.from_bytes(confirmation.generate()[2:], "big") + 1001 == confirmation.user_channel_id


@pytest.mark.parametrize("channel_count", [-1, 32])
def test_attach_confirm_rejects_invalid_channel_counts(channel_count):
    from heralding.libs.msrdp.pdu import MCSAttachUserConfirmPDU

    with pytest.raises(ValueError):
        MCSAttachUserConfirmPDU(channel_count)


@pytest.mark.parametrize("length", [0, 1, 127, 128, 255, 4096, 32767])
def test_per_length_scalar_reader(length):
    from heralding.libs.msrdp.parser import read_per_length

    # Scalar encoding, not a hand-built client packet. Complete RDP flows
    # are generated by FreeRDP in the manual container compatibility tests.
    encoded = bytes([length]) if length < 128 else (length | 0x8000).to_bytes(2, "big")
    assert read_per_length(encoded, 0) == (length, len(encoded))


@pytest.mark.parametrize("maximum", [None, "TLSv1_2", "TLSv1_3"])
async def test_rdp_tls_ceiling_default_and_explicit_override(tmp_path, monkeypatch, sink, maximum):
    import ssl

    from heralding.honeypot import Honeypot
    from heralding.tests.conftest import load_default_config

    monkeypatch.chdir(tmp_path)
    config = load_default_config()
    cap = config["capabilities"]["rdp"]
    cap["port"] = 0
    if maximum:
        cap["protocol_specific_data"]["tls_max_version"] = maximum
    config["capabilities"] = {"rdp": cap}
    honeypot = Honeypot(config)
    try:
        await honeypot.start()
        assert honeypot._capabilities[0].tls_context.maximum_version == getattr(
            ssl.TLSVersion, maximum or "TLSv1_2"
        )
    finally:
        await honeypot.stop()
        from heralding.capabilities.handlerbase import HandlerBase

        HandlerBase.set_persona(None)
