import pytest

from heralding.tests.conftest import make_options

# RDP logins are verified manually with xfreerdp (see the milestone C plan, rule 5);
# robustness is covered by test_fuzz.py.


def _rdp_options(**extra):
    return make_options(
        banner="",
        cert={
            "common_name": "*",
            "country": "US",
            "state": "None",
            "locality": "None",
            "organization": "None",
            "organizational_unit": "None",
            "valid_days": 365,
            "serial_number": 0,
        },
        **extra,
    )


def test_tls_server_data_has_no_proprietary_rsa_material():
    import struct

    from heralding.libs.msrdp.pdu import ServerData

    # Inspect generated server data only; client wire validation uses FreeRDP.
    data = ServerData.generate(1, channel_count=4)
    pos = 0
    blocks = {}
    while pos < len(data):
        kind, length = struct.unpack_from("<HH", data, pos)
        blocks[kind] = data[pos : pos + length]
        pos += length
    assert len(blocks[0x0C02]) == 12
    assert struct.unpack_from("<II", blocks[0x0C02], 4) == (0, 0)
    assert struct.unpack_from("<HH", blocks[0x0C03], 4) == (1003, 4)
    assert struct.unpack_from("<4H", blocks[0x0C03], 8) == (1004, 1005, 1006, 1007)


@pytest.mark.parametrize("length", [0, 1, 127, 128, 255, 4096, 32767])
def test_per_length_scalar_reader(length):
    from heralding.libs.msrdp.parser import read_per_length

    # Scalar encoding, not a hand-built client packet. Complete RDP flows
    # are generated by FreeRDP in the manual container compatibility tests.
    encoded = bytes([length]) if length < 128 else (length | 0x8000).to_bytes(2, "big")
    assert read_per_length(encoded, 0) == (length, len(encoded))


async def test_rdp_optional_tls_ceiling(tmp_path, monkeypatch, sink):
    import ssl

    from heralding.honeypot import Honeypot
    from heralding.tests.conftest import load_default_config

    monkeypatch.chdir(tmp_path)
    config = load_default_config()
    cap = config["capabilities"]["rdp"]
    cap["port"] = 0
    cap["protocol_specific_data"]["tls_max_version"] = "TLSv1_2"
    config["capabilities"] = {"rdp": cap}
    honeypot = Honeypot(config)
    try:
        await honeypot.start()
        assert honeypot._capabilities[0].tls_context.maximum_version == ssl.TLSVersion.TLSv1_2
    finally:
        await honeypot.stop()
        from heralding.capabilities.handlerbase import HandlerBase

        HandlerBase.set_persona(None)
